startTime, endTime and orderId extra notes for allOrders endpoint
binance/binance-spot-api-docs pull request #38
Opened 2021-03-29 02:23 UTC by mpetrinidev

I've added some extra notes for the `allOrders` endpoint.

I received the following error when I sent the same value for startTime and endTime parameters.

> Code: 1102  
> Message: Mandatory parameter 'endTime' was not sent, was empty/null, or malformed.

endTime has to be greater than startTime (which makes sense, but the error reporting is not very clear)

--- 

And the second note is related to when you used either orderId or (startTime and endTime) optional parameters.

These notes can be helpful to avoid extra calls to Binance API.

2021-03-29 18:52 UTC, alisscco approved these changes

2021-03-31 01:08 UTC, 2pd requested changes

2021-03-31 01:08 UTC, 2pd commented on rest-api.md
> +* Either `orderId` or (`startTime` and `endTime`) must be sent when used these optional parameters.
This is not correct as `orderId` or (`startTime` and `endTime`) can be omitted.

2021-03-31 01:54 UTC, adderall-prozac commented on rest-api.md
> +* Either `orderId` or (`startTime` and `endTime`) must be sent when used these optional parameters.
We'll add a clarification on this though for future reference though. Thank you.

2021-03-31 02:05 UTC, alisscco commented
Noted ...
Please if I may ask you to specify which nodes?
For which pool or all ?
Or just binance ?
Sorry for the ignorance in this. ,
Regards,

On Wed, 31 Mar 2021 at 04:54 Prozac is fine ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In rest-api.md
> <https://github.com/binance/binance-spot-api-docs/pull/38#discussion_r604541153>
> :
>
> > @@ -1310,6 +1310,8 @@ timestamp | LONG | YES |
>  **Notes:**
>  * If `orderId` is set, it will get orders >= that `orderId`. Otherwise most recent orders are returned.
>  * For some historical orders `cummulativeQuoteQty` will be < 0, meaning the data is not available at this time.
> +* If `startTime` and `endTime` are set, `endTime` has to be greater than `startTime`.
> +* Either `orderId` or (`startTime` and `endTime`) must be sent when used these optional parameters.
>
> We'll add a clarification on this though for future reference though.
> Thank you.
>
> —
> You are receiving this because you commented.
>
>
> Reply to this email directly, view it on GitHub
> <https://github.com/binance/binance-spot-api-docs/pull/38#discussion_r604541153>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AS3AD2HU3EFLTV5VSOIZR33TGJ6GRANCNFSM4Z6WHBHQ>
> .
>

2021-03-31 02:17 UTC, mpetrinidev commented on rest-api.md
> +* Either `orderId` or (`startTime` and `endTime`) must be sent when used these optional parameters.
I've meant if you only sent either `orderId` or (`startTime` and `endTime`). You cannot use all parameters together.

2021-03-31 02:18 UTC, alisscco commented
On it ..

On Wed, 31 Mar 2021 at 05:04 ali mazloum ***@***.***> wrote:

> Noted ...
> Please if I may ask you to specify which nodes?
> For which pool or all ?
> Or just binance ?
> Sorry for the ignorance in this. ,
> Regards,
>
> On Wed, 31 Mar 2021 at 04:54 Prozac is fine ***@***.***>
> wrote:
>
>> ***@***.**** commented on this pull request.
>> ------------------------------
>>
>> In rest-api.md
>> <https://github.com/binance/binance-spot-api-docs/pull/38#discussion_r604541153>
>> :
>>
>> > @@ -1310,6 +1310,8 @@ timestamp | LONG | YES |
>>  **Notes:**
>>  * If `orderId` is set, it will get orders >= that `orderId`. Otherwise most recent orders are returned.
>>  * For some historical orders `cummulativeQuoteQty` will be < 0, meaning the data is not available at this time.
>> +* If `startTime` and `endTime` are set, `endTime` has to be greater than `startTime`.
>> +* Either `orderId` or (`startTime` and `endTime`) must be sent when used these optional parameters.
>>
>> We'll add a clarification on this though for future reference though.
>> Thank you.
>>
>> —
>> You are receiving this because you commented.
>>
>>
>> Reply to this email directly, view it on GitHub
>> <https://github.com/binance/binance-spot-api-docs/pull/38#discussion_r604541153>,
>> or unsubscribe
>> <https://github.com/notifications/unsubscribe-auth/AS3AD2HU3EFLTV5VSOIZR33TGJ6GRANCNFSM4Z6WHBHQ>
>> .
>>
>

2021-03-31 02:53 UTC, 2pd commented
We have made the change at #39 , thanks for feedback.

2021-03-31 02:53 UTC, closed without merging

2021-03-31 03:59 UTC, alisscco commented on rest-api.md
> +* Either `orderId` or (`startTime` and `endTime`) must be sent when used these optional parameters.
Trying to figure it out .. I didn't do it on purpose ..

2021-03-31 03:59 UTC, alisscco commented on rest-api.md
> +* Either `orderId` or (`startTime` and `endTime`) must be sent when used these optional parameters.
Trying to figure it out .. I didn't do it on purpose ..